import { formatTokens } from '../tokens.js';
import type { AgentReport, McpServerResult, Report, Source } from '../types.js';
import { pctText } from './pretty.js';
import { offenders } from './shared.js';

function esc(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function sourceRow(s: Source, servers: Map<string, McpServerResult>): string {
  if (s.kind === 'mcp') {
    const r = s.serverKey ? servers.get(s.serverKey) : undefined;
    if (!r || r.status !== 'ok') {
      return `| mcp | \`${esc(s.name)}\` | ${r ? r.status : 'n/a'} | — |`;
    }
    return `| mcp | \`${esc(s.name)}\` | ${r.toolCount} tools (${r.transport}) | ${formatTokens(r.tokens)} |`;
  }
  const detail = s.kind === 'import' && s.parent ? `via \`${esc(s.parent)}\`` : s.note ? esc(s.note) : '';
  return `| ${s.kind} | \`${esc(s.displayPath ?? s.name)}\` | ${detail} | ${formatTokens(s.tokens)} |`;
}

function agentDetails(a: AgentReport, servers: Map<string, McpServerResult>): string[] {
  const out: string[] = [];
  out.push(`<details><summary><b>${a.name}</b> — ≈${formatTokens(a.totalTokens)} tokens</summary>`, '');
  const always = a.sources.filter((s) => s.loading === 'always');
  const rows: { tokens: number; line: string }[] = [];
  for (const s of always) {
    if (s.kind === 'skill' || s.kind === 'subagent' || s.kind === 'command') continue;
    const failed = s.kind === 'mcp' && servers.get(s.serverKey ?? '')?.status !== 'ok';
    rows.push({ tokens: failed ? -1 : s.tokens, line: sourceRow(s, servers) });
  }
  for (const kind of ['skill', 'subagent', 'command'] as const) {
    const list = always.filter((s) => s.kind === kind);
    if (!list.length) continue;
    const total = list.reduce((n, s) => n + s.tokens, 0);
    const onDemand = list.reduce((n, s) => n + (s.onDemandTokens ?? 0), 0);
    rows.push({
      tokens: total,
      line: `| ${kind} | ${list.length} ${kind}${list.length === 1 ? '' : 's'} (descriptions) | +${formatTokens(onDemand)} on demand | ${formatTokens(total)} |`,
    });
  }
  rows.sort((x, y) => y.tokens - x.tokens);
  out.push('| Type | Source | Details | ≈Tokens |', '|---|---|---|---:|');
  for (const r of rows) out.push(r.line);
  out.push('');
  const cond = a.sources.filter((s) => s.loading === 'conditional');
  if (cond.length) out.push(`_+ ${cond.length} conditional rule(s), ≈${formatTokens(a.conditionalTokens)} tokens, loaded only when relevant._`, '');
  if (a.notes.length) out.push(a.notes.map((n) => `> ${n}`).join('<br>\n'), '');
  out.push('</details>', '');
  return out;
}

export function renderMarkdown(report: Report): string {
  const servers = new Map(report.mcpServers.map((s) => [s.key, s]));
  const agents = report.agents.filter((a) => a.detected || a.totalTokens > 0);
  const out: string[] = [];
  out.push('## context-diet report', '');
  out.push(
    `Always-loaded context per agent (≈ tokens, o200k_base) against a ${formatTokens(report.window)}-token window.`,
    '',
  );
  const budget = report.budget.maxTokens;
  out.push(`| Agent | ≈Tokens | % of window |${budget != null ? ' Budget |' : ''}`);
  out.push(`|---|---:|---:|${budget != null ? ':---:|' : ''}`);
  for (const a of agents) {
    const b = budget != null ? ` ${a.overBudget ? `❌ > ${formatTokens(budget)}` : '✅'} |` : '';
    out.push(`| ${a.name} | ${formatTokens(a.totalTokens)} | ${pctText(a.totalTokens, report.window)} |${b}`);
  }
  if (!agents.length) out.push('| _no agent configuration found_ | | |');
  out.push('');

  for (const a of agents) out.push(...agentDetails(a, servers));

  const top = offenders(report, 5);
  if (top.length) {
    out.push('### Top offenders', '');
    top.forEach((o, i) => out.push(`${i + 1}. \`${esc(o.label)}\` (${o.kind}) — ≈${formatTokens(o.tokens)} tokens · ${o.agents.join(', ')}`));
    out.push('');
  }
  if (report.suggestions.length) {
    out.push('### Suggestions', '');
    for (const s of report.suggestions) out.push(`- **${s.severity}** — ${s.message}`);
    out.push('');
  }
  if (budget != null && report.budget.exceeded.length) {
    const names = report.budget.exceeded.map((id) => report.agents.find((a) => a.id === id)!.name);
    out.push(`**Budget exceeded** (${formatTokens(budget)} tokens): ${names.join(', ')}`, '');
  }
  out.push(`<sub>Generated by [context-diet](https://github.com/paulochastinet/context-diet) v${report.tool.version}</sub>`, '');
  return out.join('\n');
}
